In [1]:
from xgboost import XGBClassifier

/Users/happyeon/opt/anaconda3/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [2]:
import pandas as pd
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()

In [3]:
pd.DataFrame(data = iris.data, columns = iris.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [4]:
df = pd.DataFrame(data= np.c_[iris['data'] , iris['target']], columns=[iris.feature_names + ['target']] )

In [5]:
df.head(2)

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm) target
0               5.1              3.5               1.4              0.2    0.0
1               4.9              3.0               1.4              0.2    0.0

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris['data'], iris['target'], random_state=2)

In [7]:
from sklearn.metrics import accuracy_score

In [8]:
xgb = XGBClassifier(booster='gbtree', object = 'multi:softprob', max_depth = 6,
                learning_rate = 0.1, n_estimators = 100, n_job = -1)

In [9]:
xgb.fit(X_train,y_train)

[11:13:59] WARNING: ../src/learner.cc:576: 
Parameters: { "n_job", "object" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[11:13:59] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


/Users/happyeon/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_delta_step=0,
              max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_job=-1, n_jobs=8,
              num_parallel_tree=1, object='multi:softprob',
              objective='multi:softprob', predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, ...)

In [10]:
xgb.predict(X_test)

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 1,
       2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1])

In [11]:
y_test

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1])

In [12]:
accuracy_score(xgb.predict(X_test),y_test)

0.9736842105263158

In [13]:
X,y = datasets.load_diabetes(return_X_y = True)

In [14]:
X.shape

(442, 10)

In [15]:
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor

In [16]:
xgb_reg = XGBRegressor(booster = 'gbtree', objective='reg:squarederror', max_depth = 6,
             learning_rate = 0.1, n_estimators = 100, n_jobs = -1)

In [19]:
scores = cross_val_score(xgb_reg, X, y, scoring='neg_mean_squared_error', cv=5)

In [22]:
rmse = np.sqrt(-scores)

In [23]:
rmse

array([63.03324373, 59.68949026, 64.53750786, 63.69898607, 64.66097684])

In [24]:
rmse.mean()

63.12404095304173

In [27]:
pd.DataFrame(y).describe()

0
count  442.000000
mean   152.133484
std     77.093005
min     25.000000
25%     87.000000
50%    140.500000
75%    211.500000
max    346.000000

In [34]:
df = pd.read_csv('/Users/happyeon/Downloads/atlas-higgs-challenge-2014-v2.csv.gz')

In [35]:
df.head()

EventId  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  DER_pt_h  \
0   100000       138.470                       51.655        97.827    27.980   
1   100001       160.937                       68.768       103.235    48.146   
2   100002      -999.000                      162.172       125.953    35.635   
3   100003       143.905                       81.417        80.943     0.414   
4   100004       175.864                       16.915       134.805    16.405   

   DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0                  0.91           124.711                2.666   
1               -999.00          -999.000             -999.000   
2               -999.00          -999.000             -999.000   
3               -999.00          -999.000             -999.000   
4               -999.00          -999.000             -999.000   

   DER_deltar_tau_lep  DER_pt_tot  ...  PRI_jet_leading_eta  \
0               3.064      41.928  ...                2.150   
1               3.473       2.078  ...                0.725   
2               3.148       9.336  ...                2.053   
3               3.310       0.414  ...             -999.000   
4               3.891      16.405  ...             -999.000   

   PRI_jet_leading_phi  PRI_jet_subleading_pt  PRI_jet_subleading_eta  \
0                0.444                 46.062                    1.24   
1                1.158               -999.000                 -999.00   
2               -2.028               -999.000                 -999.00   
3             -999.000               -999.000                 -999.00   
4             -999.000               -999.000                 -999.00   

   PRI_jet_subleading_phi  PRI_jet_all_pt    Weight  Label  KaggleSet  \
0                  -2.475         113.497  0.000814      s          t   
1                -999.000          46.226  0.681042      b          t   
2                -999.000          44.251  0.715742      b          t   
3                -999.000          -0.000  1.660654      b          t   
4                -999.000           0.000  1.904263      b          t   

   KaggleWeight  
0      0.002653  
1      2.233584  
2      2.347389  
3      5.446378  
4      6.245333  

[5 rows x 35 columns]

In [36]:
df.shape

(818238, 35)

In [37]:
label_col = df['Label']

In [38]:
df.drop(['Weight','KaggleSet','Label'], axis=1, inplace=True)

In [45]:
df.rename(columns={'KaggleWeight' : 'Weight'}, inplace=True)

In [46]:
# s -> signal(신호) , b -> background(잡음)
label_col.replace(('s', 'b'), (1,0), inplace=True)

In [50]:
X = df.iloc[ : , 1 : ] 
y = label_col

In [51]:
import xgboost as xgb

In [56]:
X

DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  DER_pt_h  \
0            138.470                       51.655        97.827    27.980   
1            160.937                       68.768       103.235    48.146   
2           -999.000                      162.172       125.953    35.635   
3            143.905                       81.417        80.943     0.414   
4            175.864                       16.915       134.805    16.405   
...              ...                          ...           ...       ...   
818233       105.668                       46.443        60.048   156.191   
818234        99.294                       30.097        62.713    65.861   
818235       108.497                        9.837        65.149    18.006   
818236        96.711                       20.006        66.942    29.761   
818237        92.373                       80.109        77.619     3.984   

        DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0                      0.910           124.711                2.666   
1                   -999.000          -999.000             -999.000   
2                   -999.000          -999.000             -999.000   
3                   -999.000          -999.000             -999.000   
4                   -999.000          -999.000             -999.000   
...                      ...               ...                  ...   
818233                 0.403            47.746                0.936   
818234                 3.312           471.319               -2.611   
818235              -999.000          -999.000             -999.000   
818236              -999.000          -999.000             -999.000   
818237              -999.000          -999.000             -999.000   

        DER_deltar_tau_lep  DER_pt_tot  DER_sum_pt  ...  PRI_met_sumet  \
0                    3.064      41.928     197.760  ...        258.733   
1                    3.473       2.078     125.157  ...        164.546   
2                    3.148       9.336     197.814  ...        260.414   
3                    3.310       0.414      75.968  ...         86.062   
4                    3.891      16.405      57.983  ...         53.131   
...                    ...         ...         ...  ...            ...   
818233               1.279       6.133     256.853  ...        303.668   
818234               2.294       2.889     248.582  ...        266.919   
818235               2.742      18.006      68.097  ...        188.648   
818236               2.479       2.739     101.676  ...        212.565   
818237               2.486       3.984      77.348  ...         97.379   

        PRI_jet_num  PRI_jet_leading_pt  PRI_jet_leading_eta  \
0                 2              67.435                2.150   
1                 1              46.226                0.725   
2                 1              44.251                2.053   
3                 0            -999.000             -999.000   
4                 0            -999.000             -999.000   
...             ...                 ...                  ...   
818233            2             112.264                1.190   
818234            2             108.698                1.293   
818235            0            -999.000             -999.000   
818236            1              30.863                1.460   
818237            0            -999.000             -999.000   

        PRI_jet_leading_phi  PRI_jet_subleading_pt  PRI_jet_subleading_eta  \
0                     0.444                 46.062                   1.240   
1                     1.158               -999.000                -999.000   
2                    -2.028               -999.000                -999.000   
3                  -999.000               -999.000                -999.000   
4                  -999.000               -999.000                -999.000   
...                     ...                    ...                     ...   
818233               -0.76

In [54]:
y.values.reshape(-1,1)

array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X,pd.DataFrame(y.values.reshape(-1,1)),test_size=0.2 , random_state=42)

In [75]:
y_test.value_counts()

0    107783
1     55865
dtype: int64

In [76]:
y_train

0
83679   0
137910  0
653204  0
576025  1
580374  0
...    ..
259178  1
365838  0
131932  0
671155  0
121958  0

[654590 rows x 1 columns]

In [77]:
xgbmat = xgb.DMatrix(X_train, y_train, missing=-999.0)

/Users/happyeon/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


In [78]:
param = {
    'objective' : 'binary:logitraw',
    'eta' : 0.1 ,
    'max_depth' : 6,
    'eval_metric' : 'auc',
}

In [79]:
bst = xgb.train(param,xgbmat,120,[(xgbmat, 'train')])

[0]	train-auc:1.00000
[1]	train-auc:1.00000
[2]	train-auc:1.00000
[3]	train-auc:1.00000
[4]	train-auc:1.00000
[5]	train-auc:1.00000
[6]	train-auc:1.00000
[7]	train-auc:1.00000
[8]	train-auc:1.00000
[9]	train-auc:1.00000
[10]	train-auc:1.00000
[11]	train-auc:1.00000
[12]	train-auc:1.00000
[13]	train-auc:1.00000
[14]	train-auc:1.00000
[15]	train-auc:1.00000
[16]	train-auc:1.00000
[17]	train-auc:1.00000
[18]	train-auc:1.00000
[19]	train-auc:1.00000
[20]	train-auc:1.00000
[21]	train-auc:1.00000
[22]	train-auc:1.00000
[23]	train-auc:1.00000
[24]	train-auc:1.00000
[25]	train-auc:1.00000
[26]	train-auc:1.00000
[27]	train-auc:1.00000
[28]	train-auc:1.00000
[29]	train-auc:1.00000
[30]	train-auc:1.00000
[31]	train-auc:1.00000
[32]	train-auc:1.00000
[33]	train-auc:1.00000
[34]	train-auc:1.00000
[35]	train-auc:1.00000
[36]	train-auc:1.00000
[37]	train-auc:1.00000
[38]	train-auc:1.00000
[39]	train-auc:1.00000
[40]	train-auc:1.00000
[41]	train-auc:1.00000
[42]	train-auc:1.00000
[43]	train-auc:1.0000

In [80]:
xgbmat_test = xgb.DMatrix(X_train, y_train, missing=-999.0)

/Users/happyeon/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


In [81]:
y_hat = bst.predict(xgbmat_test)

In [82]:
y_hat

array([-12.07885, -12.07885, -12.07885, ..., -12.07885, -12.07885,
       -12.07885], dtype=float32)

In [2]:
from lightgbm import LGBMClassifier
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

dataset = load_breast_cancer()


ftr = dataset.data
target = dataset.target

X_train, X_test, y_train, y_test = train_test_split(ftr, target, test_size=0.2 , random_state=156)


gbm = LGBMClassifier(n_estimators=400)

gbm.fit(X_train, y_train, early_stopping_rounds=100, eval_metric='logloss',
        eval_set=[(X_test, y_test)], verbose=True)

[1]	valid_0's binary_logloss: 0.565079
Training until validation scores don't improve for 100 rounds
[2]	valid_0's binary_logloss: 0.507451
[3]	valid_0's binary_logloss: 0.458489
[4]	valid_0's binary_logloss: 0.417481
[5]	valid_0's binary_logloss: 0.385507
[6]	valid_0's binary_logloss: 0.355773
[7]	valid_0's binary_logloss: 0.329587
[8]	valid_0's binary_logloss: 0.308478
[9]	valid_0's binary_logloss: 0.285395
[10]	valid_0's binary_logloss: 0.267055
[11]	valid_0's binary_logloss: 0.252013
[12]	valid_0's binary_logloss: 0.237018
[13]	valid_0's binary_logloss: 0.224756
[14]	valid_0's binary_logloss: 0.213383
[15]	valid_0's binary_logloss: 0.203058
[16]	valid_0's binary_logloss: 0.194015
[17]	valid_0's binary_logloss: 0.186412
[18]	valid_0's binary_logloss: 0.179108
[19]	valid_0's binary_logloss: 0.174004
[20]	valid_0's binary_logloss: 0.167155
[21]	valid_0's binary_logloss: 0.162494
[22]	valid_0's binary_logloss: 0.156886
[23]	valid_0's binary_logloss: 0.152855
[24]	valid_0's binary_loglo

LGBMClassifier(n_estimators=400)

In [1]:
import lightgbm as lgb
print(lgb.__version__)

3.3.5
